### ISSUE TITLE
Criar página de login

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/app-site#170]
Hoje já existe um sistema de realizar login, porém ele não está de um jeito muito bom. Precisa revisá-lo.

O ideal seria que a pessoa tivesse um login e uma conta, onde também poderia configurar uma imagem.

Depois que a pessoa faz login ela terá acesso a área logada, onde pode gerar os tickets compartilháveis dos eventos. Por enquanto não prensei em novas funcionalidades, mas vamos começar por isso.

**Comment by gabrnunes** [comment]
Ah, lembrei também que com o login a pessoa vai ter acesso aos jogos dos eventos né? Talvez podemos criar uma área de networking. Não sei hehe.

**Comment by gabrnunes** [comment]
Uma coisa que precisamos melhorar também é a forma como o login é mantido, que usávamos localStorage, devido a um problema do Gather. Temos que rever todo esse fluxo.

**Comment by Markkop** [comment]
Seria legal adicionar aqueles login pelo google e github também. Tenho usado NextAuth e é tranquilo de implementar, já vem com isso e outras coisas prontas

**Comment by gabrnunes** [comment]
Pois é, seria até legal pra já puxar a fotinho da pessoa né?
