### ISSUE TITLE
Atualizar Webhook para Even3

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/app-site#171]
Ainda preciso pedir pra eles configurarem, mas aqui está a documentação: https://drive.google.com/file/d/1hhu_-WSPy_lTPiOuPbJn6NWZ6lC-LKxM/view

Hoje já temos um Webhook que recebia os inscritos do Sympla. Dai precisamos adaptar.

**Comment by Markkop** [comment]
@gabrnunes Seria tipo aqui? https://github.com/codecon-dev/app-site/blob/897f74e53b6f77bca0317d6532880b2a6c6dfb74/pages/api/sympla/new-attendee.ts
Consegues linkar os arquivos relacionados?

**Comment by gabrnunes** [comment]
É isso ai mesmo, @Markkop! Lembro que quando alguém comprava ingresso, a gente adicionava como um usuário no nosso banco também.

A questão é que quando a pessoa ia fazer login, precisava informar o ID da compra no Sympla e depois o E-mail. Dessa forma a gente conseguia relacionar uma com a outra. Mas talvez esse fluxo possa ser revisto.

**Comment by TiagoSansao** [comment]
Só para compreender melhor o escopo e requisitos. 

É um requisito manter o state de um participante entre vários eventos da Codecon? Ou a página do participante tem a única função de ser útil ao participante durante um evento específico?

Se for apenas para um evento específico, um fluxo bem straightforward seria:
Abre a Página do participante -> (um input pedindo nº inscrição) -> Puxa dados da API da Even3 e gera um token pra autenticação nos próximos requests

Nessa situação, teria um problema de segurança grande que o Nº de inscrição seria um dado sensível, pelo menos ele não é auto incremental. Também seria necessário fazer buscas na API da even3 pelo Nº de inscrição, contudo, quando vi a doc (https://docs.even3.com.br/pessoas), aparentemente não tem o field explícito Nº do inscrição (posso estar muito cego!!!).

Não sei se viajei muito acima, também pensei em algumas outras formas. De qualquer maneira, é melhor esperar a resposta da primeira pergunta pra ver o que é válido. Até então, parece-me que o atual fluxo no Sympla é atrelado a um uso único para um só evento ` Attendee.findBySymplaIdAndEvent(id, event);`

Ps.: depois de entender melhor a codebase, acho que o que propus acima é invalido pq Attendee e User são entidades diferentes, então eu devo ter entrado em outro escopo que não é dessa task. Se alguém puder esclarecer (;

**Comment by gabrnunes** [comment]
Tava tentando lembrar pq a gente acabou criando o Attendee e o User, mas agora faz mais sentido. Um mesmo usuário (User) pode ser participante (Attendee) de vários eventos. 

A ideia é que a pessoa tenha um login único na Codecon, e quando ela entrar no dashboard apareçam os eventos que estão atrelados ao e-mail dela. Clicando em um evento ela tem as ações desse evento.

Na Codecon Summit a pessoa vai poder gerar um ticket personalizado e compartilhável, pra dizer que vai no evento. Além de ter acesso aos jogos, code-codes, etc.

Na Select Experience não teriam interações no dia do evento, somente o gerar o ticket personalizável.

Mas pensei que poderia ter também badges para cada evento que a pessoa participou. Tipo os meetups ou lives que ela se inscreveu.
